server:
  port: 9009


spring:
  rabbitmq:
    host: 47.107.177.108
    username: admin
    password: admin
    port: 5672


aliyun:
  sms:
    accessKeyId: 阿里云的accessKey
    accessSecret: 阿里云的Secret
    template_code: SMS_165413131
    sign_name: 云上myth
