server:
  port: 9001 #设置服务端口
spring:
  application:
    name: tensquare-base        # 指定服务器名称,后期SpringCloud需要使用到
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #数据库驱动
    url: jdbc:mysql://47.107.177.108:8806/tensquare_base?characterEncoding=utf-8 #链接对应的数据库
    username: root
    password: root
  jpa:
    database: mysql #数据库类型
    show-sql: true # 展示SQL语句
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.106:6868/eureka
  instance:
    prefer-ip-address: true
