server:
  port: 8888

spring:
  application:
    name: tensquare-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:conf/  # 搜索src/main/resource 下的conf文件夹下的文件


  rabbitmq:
    host: 47.107.177.108
    username: admin
    password: admin
    port: 5672



management:
  endpoints:
    web:
      exposure:
        include: bus-refresh