server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.177.108:8806/tensquare_qa?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: tensquare
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.106:6868/eureka
  instance:
    prefer-ip-address: true