server:
  port: 9006
spring:
  application:
    name: tensquare-split   #指定服务名
  data:
    mongodb:
      host: 47.107.177.108
      port: 8380
      database: splitdb
  redis:
    host: 47.107.177.108
    port: 8379